[connections.gsheets]
type = "service_account"
project_id = "aplikasi-penjahit"
private_key_id = "c679b8f32c09c41e901218d79a3e01bf6a834d57"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCi6+1uvAaeiRT7\nnAJlpnToZGRUzwujuCq6zVlXE91/JKw1WEfM2r7Ep+afk50lL0K1m1l/jefbDT1NT\nnOptMU/iZKhg7VjDSfep5Nt4DDiNDdD4IvBlzPE2VgjAzvlC7V9ywOgi6mYCm3/f\nnDt+hFGiWYC6LivxYd1en/wMgwvHUp90k+BMjWJd1tb8yI0V4T9DoUjcwFoWLykRJ\nn0c48/+DnxX3Z51/J/X0NQi8GqiofgExJS0M/ZQ0e1n91Qg+0gvZOk8vMci7zSC4M\nn5DzTez9nLkiv8FE302pEGSCWGlh6lz7m1HMGiYf5TBx/NKiuow/bpA=\n-----END PRIVATE KEY-----\n"
client_email = "aplikasi-penjahit@aplikasi-penjahit.iam.gserviceaccount.com"
client_id = "109833933426018082526"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/official/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/aplikasi-penjahit%40aplikasi-penjahit.iam.gserviceaccount.com"
spreadsheet = "https://docs.google.com/spreadsheets/d/1O_cUy9650qq7mlHrSispIHNGzbN_1BAtvM3SUEpOFg/edit#gid=0"
